server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: client-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.trusted.packages: "*"
      spring.json.value.default.type: java.util.Map
      spring.json.add.type.headers: false
      spring.json.use.type.headers: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres-client}:${DB_PORT:5432}/${DB_NAME:client_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    url: jdbc:postgresql://${DB_HOST:postgres-client}:${DB_PORT:5432}/${DB_NAME:client_db}

logging:
  level:
     org.aop: DEBUG
     org.springframework.aop: DEBUG
     org.springframework.context: DEBUG
     org.springframework.boot: DEBUG
  #  org.hibernate.SQL: DEBUG
   # org.hibernate.orm.jdbc.bind: TRACE
    #org.springframework.web: DEBUG
    #org.clientpr.demo: DEBUG

kafka:
  topics:
    client-products: client_products
    client-credit-products: client_credit_products
    client-cards: client_cards
    client-transactions: client_transactions
    service-logs: service_logs

credit:
  default:
    interest-rate: 15.0
    months: 24
    amount: 100000
aop:
  metric:
    execution-time-limit: 2000
  cache:
    default-ttl: 300000
    cleanup-interval: 60000