server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: account-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: account-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.value.default.type: java.util.Map
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: java.util.Map
        spring.json.add.type.headers: false
        spring.json.use.type.headers: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres-account}:${DB_PORT:5432}/${DB_NAME:account_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    url: jdbc:postgresql://${DB_HOST:postgres-account}:${DB_PORT:5432}/${DB_NAME:account_db}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.web: DEBUG
    org.accountpr.demo: DEBUG

kafka:
  topics:
    client-products: client_products
    client-cards: client_cards
    client-transactions: client_transactions
transaction:
  limits:
    max-transactions-per-card: 10
    time-window-minutes: 5
    freeze-threshold: 5
    cleanup-hours: 24
credit:
  payment:
    check-interval-hours: 24    # Проверка просроченных платежей раз в сутки
    grace-period-days: 5